task:
  container:
    dockerfile: Dockerfile
    cpu: 2
    greedy: true
  matrix:
    - name: Build
      build_script: RUSTFLAGS="-C target-feature=+crt-static" cargo build --target x86_64-unknown-linux-gnu --release
      binaries_artifacts:
        path: target/x86_64-unknown-linux-gnu/release/cotton
    - name: Check
      script: cargo fmt -- --check && cargo clippy